export { HeroSection } from "./HeroSection";
export { AboutSection } from "./AboutSection";
export { ProctoringHighlightSection } from "./ProctoringHighlightSection";
export { BenefitsSection } from "./BenefitsSection";
export { FeaturesSection } from "./FeaturesSection";
export { PricingSection } from "./PricingSection";
export { TestimonialsSection } from "./TestimonialsSection";
export { FaqSection } from "./FaqSection";
export { CtaSection } from "./CtaSection";