// src/features/proctoring/types/proctoring.types.ts

/**
 * PROCTORING TYPES - ALIGNED WITH CURRENT FRONTEND
 *
 * ✅ Includes all types used by components and stores
 * ✅ Matches backend contract
 */

// ============================================================================
// ENUMS
// ============================================================================

export type ProctoringEventType =
    | 'FACE_DETECTED'
    | 'NO_FACE_DETECTED'
    | 'MULTIPLE_FACES'
    | 'LOOKING_AWAY';

export type ViolationSeverity = 'INFO' | 'LOW' | 'MEDIUM' | 'HIGH';
export type EventSeverity = ViolationSeverity; // Alias

// ============================================================================
// WEBCAM STATE
// ============================================================================

export interface WebcamState {
    isActive: boolean;
    stream: MediaStream | null;
    error: string | null;
    lastCapture: string | null;
}

// ============================================================================
// PROCTORING EVENT (backend structure)
// ============================================================================

export interface ProctoringEvent {
    id: number;
    userExamId: number;
    eventType: ProctoringEventType;
    severity: ViolationSeverity;
    timestamp: string;
    details: string | null;
    mlConfidence: number | null;
    metadata?: Record<string, any> | null; // Backend field
    autoGenerated?: boolean; // Whether logged by YOLO
    createdAt?: string;
}

// ============================================================================
// VIOLATION (UI state - different from ProctoringEvent)
// ============================================================================

export interface Violation {
    id: string;
    type: string;
    severity: ViolationSeverity;
    timestamp: string;
    message: string;
}

// ============================================================================
// PAGINATION
// ============================================================================

export interface PaginationMeta {
    page: number;
    limit: number;
    total: number;
    totalPages: number;
}

// ============================================================================
// API REQUESTS
// ============================================================================

export interface AnalyzeFaceRequest {
    imageBase64: string;
}

export interface LogEventRequest {
    userExamId: number;
    eventType: ProctoringEventType;
    metadata?: Record<string, any>;
}

export interface ProctoringEventsParams {
    page?: number;
    limit?: number;
    eventType?: ProctoringEventType;
    severity?: ViolationSeverity;
}

// ============================================================================
// API RESPONSES
// ============================================================================

/**
 * Face analysis response from YOLO
 */
export interface AnalyzeFaceResponse {
    data: {
        analysis: {
            faceDetected: boolean;
            violations: string[];
            message: string;
            confidence: number;
        };
        eventLogged: boolean;
    };
}

/**
 * Proctoring events list response
 */
export interface ProctoringEventsResponse {
    data: ProctoringEvent[];
    pagination: PaginationMeta;
}

/**
 * Log event response
 */
export interface LogEventResponse {
    data: {
        event: ProctoringEvent;
    };
}

// ============================================================================
// HELPER TYPES FOR UI
// ============================================================================

export interface ViolationCounts {
    low: number;
    medium: number;
    high: number;
    total: number;
}