// src/features/proctoring/types/proctoring.types.ts

/**
 * PROCTORING TYPES - BACKEND-ALIGNED
 *
 * ✅ REFACTORED: All types match backend Prisma schema EXACTLY
 *
 * KEY FIXES:
 * - Uses shared ProctoringEventType enum
 * - Uses shared ViolationSeverity enum (only LOW/MEDIUM/HIGH, NO 'INFO')
 * - Removed non-existent fields (details, mlConfidence, autoGenerated)
 * - Backend ProctoringEvent only has: id, userExamId, eventType, timestamp, severity, metadata
 * - All dates as ISO strings
 *
 * Backend Source: backend/prisma/schema.prisma, backend/src/features/proctoring/
 */

import type { ProctoringEventType, ViolationSeverity } from '@/shared/types/enum.types';
import type { PaginatedResponse } from '@/shared/types/api.types';

// ============================================================================
// PROCTORING EVENT (from Prisma model)
// ============================================================================

/**
 * ProctoringEvent model from backend Prisma
 *
 * Backend Prisma fields ONLY:
 * - id: number
 * - userExamId: number
 * - eventType: ProctoringEventType enum
 * - timestamp: DateTime
 * - severity: string (stored as 'LOW' | 'MEDIUM' | 'HIGH')
 * - metadata: Json? (optional, can store any JSON)
 *
 * ❌ REMOVED fields that don't exist in Prisma:
 * - details (doesn't exist)
 * - mlConfidence (doesn't exist)
 * - autoGenerated (doesn't exist)
 */
export interface ProctoringEvent {
    id: number;
    userExamId: number;
    eventType: ProctoringEventType; // ✅ Uses shared enum
    timestamp: string; // ISO datetime
    severity: ViolationSeverity; // ✅ Uses shared enum (LOW/MEDIUM/HIGH only)
    metadata: Record<string, any> | null; // JSON field - flexible structure
    // ❌ Removed: details, mlConfidence, autoGenerated (not in Prisma schema)
}

/**
 * ProctoringEvent with nested userExam info (admin view)
 * Backend returns this from admin endpoints with full relations
 */
export interface ProctoringEventWithRelations extends ProctoringEvent {
    userExam: {
        id: number;
        userId: number;
        examId: number;
        status: string;
        user: {
            id: number;
            name: string;
            email: string;
        };
        exam: {
            id: number;
            title: string;
        };
    };
}

// ============================================================================
// API REQUEST TYPES
// ============================================================================

/**
 * Analyze face request
 * POST /proctoring/exam-sessions/:sessionId/analyze-face
 */
export interface AnalyzeFaceRequest {
    imageBase64: string; // Base64-encoded JPEG/PNG image
}

/**
 * Log event request
 * POST /proctoring/events
 */
export interface LogEventRequest {
    userExamId: number;
    eventType: ProctoringEventType; // ✅ Uses shared enum
    metadata?: Record<string, any>; // Optional additional data
}

/**
 * Query params for getProctoringEvents
 * GET /proctoring/exam-sessions/:sessionId/events?page=1&limit=20&eventType=...
 */
export interface ProctoringEventsParams {
    page?: number;
    limit?: number;
    eventType?: ProctoringEventType; // ✅ Uses shared enum
    severity?: ViolationSeverity; // ✅ Uses shared enum (no 'INFO')
    startDate?: string; // ISO datetime
    endDate?: string; // ISO datetime
    sortOrder?: 'asc' | 'desc';
}

// ============================================================================
// API RESPONSE TYPES
// ============================================================================

/**
 * POST /proctoring/exam-sessions/:sessionId/analyze-face response
 *
 * Backend returns analysis result from YOLO ML service
 */
export interface AnalyzeFaceResponse {
    analysis: {
        status: 'success' | 'error' | 'timeout'; // Processing status
        violations: ProctoringEventType[]; // Array of detected violations
        confidence: number; // 0-1 confidence score
        message: string; // Human-readable message
        metadata?: {
            processingTimeMs?: number;
            modelVersion?: string;
            faceCount?: number;
            rawDetections?: any;
            error?: string;
        };
    };
    eventLogged: boolean; // Whether backend auto-logged a violation event
    eventType: ProctoringEventType | null; // Event type if logged
    usedFallback: boolean; // Whether mock analyzer was used (ML service timeout)
}

/**
 * POST /proctoring/events response
 * Returns: { success: true, data: { event: {...} }, ... }
 */
export interface LogEventResponse {
    event: ProctoringEvent;
}

/**
 * GET /proctoring/exam-sessions/:sessionId/events response
 * Returns: { success: true, data: { data: [...], pagination: {...} }, ... }
 *
 * ✅ Uses PaginatedResponse from shared types with correct field names
 */
export type ProctoringEventsResponse = PaginatedResponse<ProctoringEvent>;

/**
 * GET /admin/proctoring/events response (admin view with relations)
 * Returns: { success: true, data: { data: [...], pagination: {...} }, ... }
 */
export type AdminProctoringEventsResponse = PaginatedResponse<ProctoringEventWithRelations>;

// ============================================================================
// UI STATE TYPES (for frontend stores - NOT from backend)
// ============================================================================

/**
 * Webcam state for proctoring UI
 * This is frontend-only state, not from backend
 */
export interface WebcamState {
    isActive: boolean;
    stream: MediaStream | null;
    error: string | null;
    lastCapture: string | null; // Base64 image data
}

/**
 * Simplified violation for UI display
 * Frontend transforms ProctoringEvent into this for easier rendering
 */
export interface UIViolation {
    id: string; // Local UUID for React keys
    type: ProctoringEventType; // ✅ Uses shared enum
    severity: ViolationSeverity; // ✅ Uses shared enum
    timestamp: string; // ISO datetime
    message: string; // Human-readable message
}